apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rollout-bluegreen
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'git@github.com:lneves75/rollouts-demo.git'
    targetRevision: HEAD
    path: charts
    helm:
      parameters:
      - name: 'image.tag'
        value: blue
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated: {}
    syncOptions:
      - ApplyOutOfSyncOnly